<?php

namespace NHL\Events;

use NHL\Event;

/**
 * Class Block
 * @package NHL\Events
 */
class Block extends Event
{

    public function parse()
    {
        return parent::parse(); // TODO: Change the autogenerated stub
    }



}