<?php

namespace NHL\Events;

use NHL\Event;

/**
 * Class Block
 * @package NHL\Events
 */
class Block extends Event
{

    /**
     * @inheritdoc
     * @return mixed
     */
    public function parse()
    {
        return parent::parse(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }


}